### ISSUE TITLE
eslint fails for blueprints/blueprint/files/blueprints/name/index.js

### ISSUE THREAD

**Issue by anithri** [SpencerCDixon/redux-cli#121]
```
/home/scottp/4winds/redux-cli/blueprints/blueprint/files/blueprints/__name__/index.js
  3:24  error  Parsing error: Unexpected token

  1 | module.exports = {
  2 |   if (description) {
> 3 |   description: function() {
    |                        ^
  4 |     return '<%- description';
  5 |   },
  6 |   }
```

**Comment by anithri** [comment]
If I rename `.../__name__index.js` to `index.js.ejs` or `index.ejs` then eslint passes.

So the problem is the eslint isn't recognizing that file as an ejs file, and parses it according to the regular js rules.

I'm not excited about needing to slap .ejs over templates.  Is there some way we can configure it?

**Comment by anithri** [comment]
I'll bet the problem is the nested `<%` tags inside strings inside other.  And jest just can't handle the parsing.

files that generate files that can generate are much easier to accept renaming to `index.js.ejs` or `index.ejs`

**Comment by anithri** [comment]
if we morph `FileInfo#mappedPath` such that if the file ends in `.ejs` it gets saved with that stripped off.

If we want to allow just .ejs files, a special case for that would need to be added, but it's easy to implement.

**Comment by jamesr73** [comment]
eslint is linting the js files because it was asked to :wink: It's using an ejs plugin to strip out the ejs tokens. But there's an assumption in the plugin that the result will be valid ES, so things like `<%= pascalEntityName %>` work because the raw value `pascalEntityName` is valid ES. Because the blueprint blueprint is putting conditional logic in the ejs tags simply removing the tags doesn't leave valid ES. We'll see much more of that if we add more logic to blueprints.

The nested tag isn't the issue, I saw the error before I added the inner tag.

We could have the generator strip ejs suffix (and if the copied file should itself be ejs just use file.ejs.ejs as the source suffix).

Or we could simply avoid linting the blueprint files entirely:

```
    "lint": "eslint ./src ./test ./blueprints/*/index.js",
```

**Comment by anithri** [comment]
But that doesn't explain why it does work when you change the file extension to ejs

**Comment by jamesr73** [comment]
Because eslint only looks for files with .js extension, so with ejs it just ignores the file.

**Comment by anithri** [comment]
I swear I tried removing the `./blueprints` from the eslint command it still failed. Must have imagined that.  I never could get any kind of ignore happening

I have reservations about the `eslint ./src ./test ./blueprints/*/index.js` as it would leave any extra code files at the top level unchecked.  I prefer to allow template files to be named some.ext.ejs  and we strip the final ejs off of it when we create the resulting file.

**Comment by jamesr73** [comment]
Can't argue with that. Simple fix to strip an .ejs suffix.

**Comment by anithri** [comment]
Switch to prettier, and renaming some blueprint files as *.ejs solves this issue #125
