### ISSUE TITLE
Create shared test suite for all Tasks and SubCommands to confirm they are complying with the blueprint contract

### ISSUE THREAD

**Issue by SpencerCDixon** [SpencerCDixon/redux-cli#24]
https://github.com/mochajs/mocha/wiki/Shared-Behaviours for inspiration on how to do shared tests in Node

**Comment by SpencerCDixon** [comment]
@anithri not sure what you're testing prefs are but might be worthwhile to convert test suite to Jest as that's what the community has rallied around.  Tighter integretion between redux-cli and create-react-app would be great.

Also name change to blueprint-cli or regen-cli might be worthwhile.  Open to thoughts

**Comment by anithri** [comment]
Possible testing strategy for commands/ sub-commands.

The key is to be able to test that:
1.  that the arguments are parsed correctly.
2.  that the action works correctly.

If we organize the command files differently, we could test the two pieces independently.
```
// can be tested by adding a action containing assertions, called with custom argv
export const cmdParser = commander.
                          version... // repeat for everything exepct the actions

// can be tested by adding calling directly bypassing most of commander.  
export const cmdAction = (blueprintName, entityName, command) => {...}

// do we need integration tests?  this is testing other peoples 
export default const run = (argv = ARGV) => cmdParser.action(cmdAction).parse(argv)

// and change
// require('../lib/cmd') to
require('../lib/cmd")()
```

**Comment by anithri** [comment]
any ideas? @jamesr73

**Comment by jamesr73** [comment]
#110 allows the individual pieces of the CLI to be tested independently as suggested.

Individual tests have access to a new yargs instance to avoid any interfernce. The production executable cli command simply calls this with process.argv.

The main/root command parser is tested by using yargs in headless-mode, primarily to verify usage output and invalid command handling.

Tests for sub commands (init, generate, etc) can use either headless-yargs or specific tests of the object the module exports to configure yargs. Or a mix of both. It's easiest to test the command builder sets up the correct options and usage info (i.e. help output) using yargs itself. The command handler that executes the actual SubCommand can be tested using yargs or directly by mocking the argv yargs would pass it. In either case the underlying SubCommand can be auto-mocked by jest so that it isn't executed. See test/cli/cmds/init.test.js.

Similarly for the blueprint commands. I'm putting together tests for the generic logic that builds and executes those, independent of the actual blueprints.

Testing the SubCommand functionality can and should be independent of the CLI tests.

Tests for individual blueprints can use shared test logic as detailed in the issue description. This should maybe also be part of the blueprint command itself. E.g.

```blueprint validate <blueprint>```

**Comment by anithri** [comment]
Refer to #120 for further discussion of `blueprint validate <blueprint>`

Closing now that #110 is merged
