### ISSUE TITLE
redux new project-name shows "Fetching ... react-redux-starter-kit.git from github" for a long time

### ISSUE THREAD

**Issue by carise** [SpencerCDixon/redux-cli#32]
Hi,

I am running redux 1.3.2 and trying to do the "redux new [project-name]". It shows these messages:

```
  info: Creating new directory...
  create: Created directory: test-proj
  info: Setting up tracking with git...
  loading: Fetching git@github.com:davezuko/react-redux-starter-kit.git from git  loading: 
  Fetching git@github.com:davezuko/react-redux-starter-kit.git from git  loading: 
  Fetching git@github.com:davezuko/react-redux-starter-kit.git from github. ⠸
The authenticity of host 'github.com (192.30.252.129)' can't be established.
  loading: Fetching git@github.com:davezuko/react-redux-starter-kit.git from git
```
and the window buffer just keeps showing ``Fetching git@github.com:davezuko/react-redux-starter-kit.git from git``. I even waited 10 minutes and I just see those same lines scrolling by. Finally, I did a ctrl-c to see if there's anything actually getting saved into my "test-proj" directory. The only thing I see is the .git directory. In the directory where test-proj is, I see that redux-cli created a .reduxrc file, i.e.

```
/projects
   +--> .reduxrc
   +--> test-proj/
          +--> .git/
```

What am I doing wrong here?

**Comment by SpencerCDixon** [comment]
Nope not doing anything wrong!  The cli assumes you have ssh setup with github. [See this issue here](https://github.com/Carthage/Carthage/issues/217).  In order to get it working you can [follow along with these instructions](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/)

In the future I'd like to have the CLI clone a local copy of the starter kit but it makes it hard to support many starter kits if I do that so its just `git pulling` the starter hit URI [here](https://github.com/SpencerCDixon/redux-cli/blob/master/src/sub-commands/new.js#L25) .

If it's still not working after setting up SSH lemme know!

**Comment by SpencerCDixon** [comment]
I'll look into providing better error message with why it borked

**Comment by carise** [comment]
Sweet! It worked! Thanks so much. Your instructions worked just perfectly.
