### ISSUE TITLE
Creating multiple smart component is failing ?

### ISSUE THREAD

**Issue by iroy2000** [SpencerCDixon/redux-cli#68]
I'm trying to play around this cli tool, and I create a smart component

```
roy :: ~/development/poc/redux-cli/test (master) $ redux g smart CommentContainer
  info: installing blueprint...
  create: /Users/roy/development/poc/redux-cli/test/src/containers/CommentContainer.js
  create: /Users/roy/development/poc/redux-cli/test/src/containers/index.js
  create: /Users/roy/development/poc/redux-cli/test/tests/containers/CommentContainer.spec.js

```

And I create another one, and it is failed, is that expected?

```
roy :: ~/development/poc/redux-cli/test (master) $ redux g smart CommentContainer2
  info: installing blueprint...
  create: /Users/roy/development/poc/redux-cli/test/src/containers/CommentContainer2.js
  error: Not writing file.  File already exists at: /Users/roy/development/poc/redux-cli/test/src/containers/index.js
  create: /Users/roy/development/poc/redux-cli/test/tests/containers/CommentContainer2.spec.js
```

**Comment by SpencerCDixon** [comment]
Is this still failing or is it resolved?

**Comment by iroy2000** [comment]
This one is still failing, have you tried that test case ?

```
redux g smart CommentContainer
redux g smart CommentContainer2
```

**Comment by SpencerCDixon** [comment]
Yeah so it's an issue in the react-redux-starter-kit's blueprint.  The blueprint file structure is currently: `__root__/containers/__name__.js` but needs to be: `__root__/containers/__name__/__name__.js` so that way each smart container has its own folder.  Right now it's trying to create multiple containers in the same folder but you can't have two `index.js`'s in that one top level folder. 

My guess is this issue is fixed on a newer branch of the starter kit (one reason I really need to tie redux-cli to a specific version of the starter kit)  

@davezuko and I are going to be fixing the blueprints for the new and improved fractal file structure.  So this issue should go away once that happens.  [You can follow along here](https://github.com/davezuko/react-redux-starter-kit/issues/734#issuecomment-216254378)

**Comment by SpencerCDixon** [comment]
Closing this since I can't actually fix this on the current repo.  This is an implementation detail of which blueprint is being used
