### ISSUE TITLE
Configuration for components/__tests__

### ISSUE THREAD

**Issue by qmmr** [SpencerCDixon/redux-cli#71]
I love the idea of redux-cli. I use snippets to create boilerplates but having a generator on the command line - priceless. My folder structure is like:
```
root
├── components
│   ├──Foo.js
│   ├──__tests__
│      ├──Foo.test.js
├── containers
│   ├──__tests__
├── reducers
│   ├──__tests__
└── index.js
```

Is there a way to configure the paths so that `__tests__` point to the subfolder of the parent folder?

**Comment by lewisf** [comment]
+1

**Comment by SpencerCDixon** [comment]
Yeah this is totally doable!

First let me re-iterate the question to make sure I'm understanding what exactly you'd like to do:

When you run `redux g dumb MyComponent` you want the  `MyComponent.test.js` file to live inside a `__tests__` folder that is nested in the `components` folder?

If so, to implement that you can override the default blueprints that come with the CLI and/or the starter kit.  To do that you just need to create a local `blueprints` folder in your project root OR modify a blueprint that is already your project root (if using the starter kit).  You would want to change the blueprint for `dumb` to look like this:

```
  1 dumb
      2 ├── files
      3 │   └── __root__
      4 │       └── __dumb__
      5 │           ├── __test__
      6 │           │   └── __name__.test.js
      7 │           └── __name__.js
      8 └── index.js
```

Now we have a little bit of an issue because the `__test__` token is going to be automatically converted to whatever your `testBase` is.  However, we can take advantage of the 'hooks' inside each blueprints `index.js` to modify functionality.  So inside the `index.js` file for the `dumb` blueprint you could do this:

```
module.exports = {
  description() {
    return 'Generates a dumb (aka Pure) component';
  },
  fileMapTokens() {
    return {
      __test__: (options) => {
        return '__test__';
      }
    };
  }
};
```

This essentially overrides the default behavior and says that when mapping the files to be generated leave the `__test__` token alone and use the STRING '__test__' for the folder name.

Hope this makes sense, let me know if you have any questions!

**Comment by qmmr** [comment]
Hi Spencer,
Thanks, works like a charm! I had to add the path to `__dumb__` compoents as well, like so: 

```
module.exports = {
  description() {
    return 'Generates a dumb (aka Pure) component';
  },
  fileMapTokens() {
    return {
      __test__: (options) => '__tests__',
      __dumb__: (options) => 'components',
    };
  }
};
```
👍

**Comment by SpencerCDixon** [comment]
Awesome, glad you got it working!
